export const products = [
  {
    id: 1,
    title: 'Organic Green Tea',
    price: 12.99,
    rating: 4.8,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&h=800&fit=crop&auto=format',
    description: 'Small-batch sencha with a clean grassy finish, packed in a resealable kraft pouch.',
    origin: 'Nilgiri hills',
    note: 'Best steeped for 2 minutes',
    inStock: true,
  },
  {
    id: 2,
    title: 'Raw Almond Butter',
    price: 8.49,
    rating: 4.9,
    category: 'Nuts & Seeds',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&h=800&fit=crop&auto=format',
    description: 'Stone-ground almond butter made from roasted organic almonds with no refined sugar.',
    origin: 'Coastal California',
    note: 'Stir before serving',
    inStock: true,
  },
  {
    id: 3,
    title: 'Organic Blueberries',
    price: 6.99,
    rating: 4.7,
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=800&h=800&fit=crop&auto=format',
    description: 'Plump organic blueberries picked ripe and chilled quickly for better texture.',
    origin: 'Pacific Northwest',
    note: 'Ships chilled',
    inStock: true,
  },
  {
    id: 4,
    title: 'Cold Pressed Olive Oil',
    price: 18.99,
    rating: 4.9,
    category: 'Oils',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&h=800&fit=crop&auto=format',
    description: 'Extra virgin olive oil pressed within hours of harvest for a peppery finish.',
    origin: 'Crete, Greece',
    note: 'First cold press',
    inStock: true,
  },
  {
    id: 5,
    title: 'Organic Honey',
    price: 14.99,
    rating: 4.8,
    category: 'Sweeteners',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&h=800&fit=crop&auto=format',
    description: 'Raw wildflower honey from organic apiaries, unpasteurized and gently strained.',
    origin: 'Western Ghats',
    note: 'Naturally crystallizes',
    inStock: true,
  },
  {
    id: 6,
    title: 'Organic Quinoa',
    price: 9.99,
    rating: 4.6,
    category: 'Grains',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&h=800&fit=crop&auto=format',
    description: 'Pre-rinsed organic white quinoa with a fluffy bite and mild nutty taste.',
    origin: 'Andean plateau',
    note: 'Ready in 15 minutes',
    inStock: true,
  },
  {
    id: 9,
    title: 'Organic Paddy',
    price: 7.49,
    rating: 4.7,
    category: 'Grains',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=500&h=500&fit=crop&auto=format',
    description: 'Naturally grown paddy from seasonal fields, cleaned and packed for traditional home milling.',
    origin: 'Godavari delta farms',
    note: 'Single-season harvest',
    inStock: true,
  },
  {
    id: 10,
    title: 'Organic Green Grams',
    price: 5.99,
    rating: 4.8,
    category: 'Grains',
    image: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=500&h=500&fit=crop&auto=format',
    description: 'Whole green grams sorted for sprouting, pesarattu batter, and everyday dal recipes.',
    origin: 'Rayalaseema dry farms',
    note: 'Great for sprouting',
    inStock: true,
  },
  {
    id: 11,
    title: 'Organic Red Grams',
    price: 6.49,
    rating: 4.8,
    category: 'Grains',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&h=500&fit=crop&auto=format',
    description: 'Protein-rich red grams selected for hearty dal, sambar, and slow-cooked curries.',
    origin: 'Telangana plateau',
    note: 'Stone-cleaned batch',
    inStock: true,
  },
  {
    id: 12,
    title: 'Organic Jonnalu',
    price: 4.99,
    rating: 4.6,
    category: 'Grains',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&h=500&fit=crop&auto=format',
    description: 'Whole jonnalu with a naturally earthy bite, ideal for rotis, porridge, and flour milling.',
    origin: 'Deccan millet belt',
    note: 'High-fiber millet',
    inStock: true,
  },
  {
    id: 13,
    title: 'Organic Rhagulu',
    price: 5.29,
    rating: 4.7,
    category: 'Grains',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=500&h=500&fit=crop&auto=format',
    description: 'Wholesome ragi grains for malt, dosa batter, and nutrient-dense everyday meals.',
    origin: 'Karnataka highlands',
    note: 'Calcium-rich grain',
    inStock: true,
  },
  {
    id: 14,
    title: 'Organic Minumullu',
    price: 6.99,
    rating: 4.9,
    category: 'Grains',
    image: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=500&h=500&fit=crop&auto=format',
    description: 'Cleaned whole black gram for idli, dosa, vada, and rich dal preparations.',
    origin: 'Krishna river basin',
    note: 'Soaks evenly',
    inStock: true,
  },
  {
    id: 15,
    title: 'Organic Shajalu',
    price: 5.79,
    rating: 4.6,
    category: 'Grains',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&h=500&fit=crop&auto=format',
    description: 'Traditional small millet with a mild flavor, useful for upma, khichdi, and porridge.',
    origin: 'Local millet growers',
    note: 'Quick-cooking millet',
    inStock: true,
  },
  {
    id: 7,
    title: 'Organic Spinach',
    price: 4.99,
    rating: 4.7,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800&h=800&fit=crop&auto=format',
    description: 'Tender organic spinach leaves washed, sorted, and packed the same morning.',
    origin: 'Local partner farms',
    note: 'Harvested daily',
    inStock: true,
  },
  {
    id: 8,
    title: 'Herbal Supplement Tea',
    price: 13.99,
    rating: 4.8,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&h=800&fit=crop&auto=format',
    description: 'Caffeine-free herbal blend with tulsi, chamomile, and lemongrass for slow evenings.',
    origin: 'Kerala herb gardens',
    note: 'Naturally caffeine-free',
    inStock: true,
  },
];

export const categories = [
  { id: 1, name: 'Beverages', image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500&h=380&fit=crop&auto=format' },
  { id: 2, name: 'Vegetables', image: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=500&h=380&fit=crop&auto=format' },
  { id: 3, name: 'Fruits', image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=500&h=380&fit=crop&auto=format' },
  { id: 4, name: 'Grains', image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=500&h=380&fit=crop&auto=format' },
  { id: 5, name: 'Nuts & Seeds', image: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=500&h=380&fit=crop&auto=format' },
  { id: 6, name: 'Oils', image: 'https://images.unsplash.com/photo-1628557044797-f21a177c37ec?w=500&h=380&fit=crop&auto=format' },
];

export const testimonials = [
  {
    id: 1,
    name: 'Sarah Johnson',
    role: 'Nutritionist',
    text: 'Orgo has completely transformed my family\'s eating habits. The quality of organic products is outstanding!',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
  },
  {
    id: 2,
    name: 'Michael Chen',
    role: 'Fitness Coach',
    text: 'I recommend Orgo to all my clients. Fresh, organic, and delivered right to your door. Perfect!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 3,
    name: 'Emma Williams',
    role: 'Health Blogger',
    text: 'The convenience and quality make Orgo my go-to for organic shopping. Highly recommended!',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
  },
];

export const benefits = [
  {
    id: 1,
    title: 'Certified Organic',
    description: 'Carefully sourced products grown without synthetic pesticides or harsh additives.',
    icon: 'Sprout',
  },
  {
    id: 2,
    title: 'Low-Waste Supply',
    description: 'Reusable packing materials and direct farm partnerships reduce unnecessary waste.',
    icon: 'Leaf',
  },
  {
    id: 3,
    title: 'Checked for Freshness',
    description: 'Every batch is inspected before dispatch so your pantry feels genuinely stocked.',
    icon: 'BadgeCheck',
  },
  {
    id: 4,
    title: 'Fast Delivery',
    description: 'Fresh groceries are packed with care and sent quickly to your doorstep.',
    icon: 'Truck',
  },
];
